# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.11

repos:
-   repo: https://github.com/adamchainz/django-upgrade
    rev: "1.16.0"  # replace with latest tag on GitHub
    hooks:
    -   id: django-upgrade
        args: [--target-version, "5.0"]   # Replace with Django version

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: check-merge-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-toml
    -   id: requirements-txt-fixer
    # -   id: check-case-conflict
    #-   id: name-tests-test

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-bugbear==23.9.16
        -   flake8-no-pep420==2.7.0
        -   flake8-comprehensions==3.14.0
        -   flake8-print==5.0.0
        -   flake8-logging==1.6.0

-   repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
    -   id: djcss
    -   id: djjs
    -   id: djhtml
        args:
        -   --tabwidth=2

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: "24.3.0"
    hooks:
    - id: black

-   repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
    - id: blacken-docs
      additional_dependencies:
      - black==23.10.0

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
    -   id: pyupgrade
        args: [--py312-plus]
