# Generated by Django 5.1.3 on 2024-11-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeedLibrary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_created=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("latin_name", models.CharField(max_length=75)),
                ("english_name", models.CharField(max_length=75)),
                ("french_name", models.CharField(max_length=75)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
