# Generated by Django 5.1.3 on 2024-11-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seedlibrary",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
