# Generated by Django 5.1.3 on 2024-11-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_seedlibrary_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="light_from",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="light_to",
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
