# Generated by Django 5.1.3 on 2024-12-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_alter_plantcollection_options_plantimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantMorphology",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("element", models.CharField(blank=True, max_length=75, unique=True)),
            ],
        ),
    ]
