# Generated by Django 5.1.3 on 2024-11-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_seedlibrary_light_from_seedlibrary_light_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="bloom_end",
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="bloom_start",
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
