# Generated by Django 5.1.3 on 2024-11-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_seedlibrary_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="soil_humidity_max",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="soil_humidity_min",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
