# Generated by Django 5.1.3 on 2024-11-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_seedlibrary_soil_humidity_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="max_height",
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="min_height",
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
