# Generated by Django 5.1.3 on 2025-01-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_sharingpriority_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="taxon",
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
