# Generated by Django 5.1.3 on 2025-01-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_plantprofile_taxon"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="inaturalist_taxon",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
