# Generated by Django 5.1.3 on 2024-11-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_seedlibrary_max_height_seedlibrary_min_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="size",
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
