# Generated by Django 5.1.3 on 2025-01-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_plantprofile_inaturalist_taxon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantprofile",
            name="inaturalist_taxon",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
