# Generated by Django 5.1.3 on 2024-11-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_seedlibrary_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="stratification_detail",
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="stratification_duration",
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
