# Generated by Django 5.1.3 on 2025-01-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_alter_plantprofile_inaturalist_taxon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="salt_tolerent",
            new_name="salt_tolerant",
        ),
    ]
