# Generated by Django 5.1.3 on 2024-11-16 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_seedlibrary_sowing_depth_seedlibrary_sowing_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharingPriority",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("sharing_priority", models.CharField(blank=True, max_length=75)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="sharing_priority",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to="project.sharingpriority"
            ),
        ),
    ]
