# Generated by Django 5.1.3 on 2025-01-15 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0011_rename_deer_tolerent_plantprofile_deer_tolerant"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="draught_tolerent",
            new_name="drought_tolerant",
        ),
    ]
