# Generated by Django 5.1.3 on 2025-02-10 19:54

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0012_rename_draught_tolerent_plantprofile_drought_tolerant"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpreadRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("spreading_rate", models.CharField(blank=True, max_length=15)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelManagers(
            name="plantprofile",
            managers=[
                ("search_plant", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name="plantprofile",
            name="hyperlink",
        ),
        migrations.RemoveField(
            model_name="plantprofile",
            name="pods_seed_head_picture_link",
        ),
        migrations.RemoveField(
            model_name="plantprofile",
            name="seed_picture_link",
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="accepting_donations",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="acidic_soil_tolerant",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="alternative_to_notes",
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="bee_friendly",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="butterfly_friendly",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="foot_traffic_tolerant",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="harvesting_notes",
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="hummingbird_friendly",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="lifespan",
            field=models.CharField(
                blank=True, choices=[("A", "Annual"), ("B", "Biennial"), ("P", "Perennial")], max_length=1
            ),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="limestone_tolerant",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="max_width",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="min_width",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="nitrogen_fixer",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="rabbit_tolerant",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="sand_tolerant",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="seed_cleaning_notes",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="sowing_label_instructions",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="sowing_notes",
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="toxicity_notes",
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="transplanting_notes",
            field=models.CharField(blank=True, max_length=450),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="max_height",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="min_height",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="spreading_rate",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to="project.spreadrate"
            ),
        ),
    ]
