# Generated by Django 5.1.3 on 2024-11-16 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0012_seedlibrary_haresting_end_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seedlibrary",
            old_name="haresting_end",
            new_name="harvesting_end",
        ),
        migrations.RenameField(
            model_name="seedlibrary",
            old_name="haresting_start",
            new_name="harvesting_start",
        ),
    ]
