# Generated by Django 5.1.3 on 2025-02-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0013_spreadrate_alter_plantprofile_managers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantprofile",
            name="harvesting_end",
        ),
    ]
