# Generated by Django 5.1.3 on 2024-11-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0013_rename_haresting_end_seedlibrary_harvesting_end_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HarvestingIndicator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("harvesting_indicator", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
