# Generated by Django 5.1.3 on 2025-04-15 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0014_remove_plantprofile_harvesting_end"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="accepting_donations",
            new_name="accepting_seed",
        ),
    ]
