# Generated by Django 5.1.3 on 2025-04-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0015_rename_accepting_donations_plantprofile_accepting_seed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantprofile",
            name="light_from",
        ),
        migrations.RemoveField(
            model_name="plantprofile",
            name="light_to",
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="full_shade",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="full_sun",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="partial_sun",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
