# Generated by Django 5.1.3 on 2024-11-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0015_seedlibrary_harvesting_indicator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="harvestingindicator",
            name="harvesting_indicator",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
