# Generated by Django 5.1.3 on 2024-11-18 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0016_alter_harvestingindicator_harvesting_indicator"),
    ]

    operations = [
        migrations.CreateModel(
            name="HarvestingMean",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("harvesting_mean", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="harvesting_mean",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to="project.harvestingmean"
            ),
        ),
    ]
