# Generated by Django 5.1.3 on 2025-06-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0016_remove_plantprofile_light_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="boulevard_tolerant",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
