# Generated by Django 5.1.3 on 2025-06-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0017_plantprofile_boulevard_tolerant"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="bird_friendly",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
