# Generated by Django 5.1.3 on 2024-11-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0018_seedhead_seedlibrary_seed_head"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="remove_non_seed_material",
            field=models.BooleanField(default=False),
        ),
    ]
