# Generated by Django 5.1.3 on 2025-06-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0018_plantprofile_bird_friendly"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="cedar_hedge_replacement",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
