# Generated by Django 5.1.3 on 2025-06-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0019_plantprofile_cedar_hedge_replacement"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="juglone_tolerant",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
