# Generated by Django 5.1.3 on 2024-11-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0019_seedlibrary_remove_non_seed_material"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViablityTest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("viability_test", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="seedlibrary",
            name="remove_non_seed_material",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
