# Generated by Django 5.1.3 on 2024-11-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0020_viablitytest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viablitytest",
            name="viability_test",
            field=models.CharField(max_length=150),
        ),
    ]
