# Generated by Django 5.1.3 on 2025-06-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0020_plantprofile_juglone_tolerant"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="cause_dermatitis",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
