# Generated by Django 5.1.3 on 2025-06-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0021_plantprofile_cause_dermatitis"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="produces_burs",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
