# Generated by Django 5.1.3 on 2024-11-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0021_alter_viablitytest_viability_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viablitytest",
            name="viability_test",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
