# Generated by Django 5.1.3 on 2024-11-18 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0022_alter_viablitytest_viability_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="viability_test",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to="project.viablitytest"
            ),
        ),
    ]
