# Generated by Django 5.1.3 on 2025-06-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0022_plantprofile_produces_burs"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="school_garden_suitable",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
