# Generated by Django 5.1.3 on 2025-06-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0023_plantprofile_school_garden_suitable"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="transplantation_tolerant",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
