# Generated by Django 5.1.3 on 2024-11-19 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0024_seedstorage_seedlibrary_seed_storage"),
    ]

    operations = [
        migrations.CreateModel(
            name="OneCultivar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("one_cultivar", models.CharField(max_length=125)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="one_cultivar",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to="project.onecultivar"
            ),
        ),
    ]
