# Generated by Django 5.1.3 on 2025-06-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0024_plantprofile_transplantation_tolerant"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantLifespan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("lifespan", models.CharField(blank=True, max_length=15)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="lifespan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.plantlifespan",
            ),
        ),
    ]
