# Generated by Django 5.1.3 on 2024-11-19 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0025_onecultivar_seedlibrary_one_cultivar"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackagingMeasure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("packaging_measure", models.CharField(max_length=35)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="packaging_measure",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to="project.packagingmeasure"
            ),
        ),
    ]
