# Generated by Django 5.1.3 on 2025-06-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0026_plantconservationstatus_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlantConservationStatus",
            new_name="ConservationStatus",
        ),
    ]
