# Generated by Django 5.1.3 on 2024-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0026_packagingmeasure_seedlibrary_packaging_measure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagingmeasure",
            name="packaging_measure",
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
