# Generated by Django 5.1.3 on 2025-06-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0027_rename_plantconservationstatus_conservationstatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conservationstatus",
            old_name="status",
            new_name="conservation_status",
        ),
    ]
