# Generated by Django 5.1.3 on 2024-11-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0027_alter_packagingmeasure_packaging_measure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seedstorage",
            name="seed_storage",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
