# Generated by Django 5.1.3 on 2024-11-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0028_alter_seedstorage_seed_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seedstorage",
            name="seed_storage",
            field=models.CharField(max_length=150),
        ),
    ]
