# Generated by Django 5.1.3 on 2025-06-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0028_rename_status_conservationstatus_conservation_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Habit",
            new_name="GrowthHabit",
        ),
        migrations.AlterModelOptions(
            name="growthhabit",
            options={"ordering": ["growth_habit"]},
        ),
        migrations.RenameField(
            model_name="growthhabit",
            old_name="habit",
            new_name="growth_habit",
        ),
        migrations.RenameField(
            model_name="plantprofile",
            old_name="habit",
            new_name="growth_habit",
        ),
    ]
