# Generated by Django 5.1.3 on 2025-06-21 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0029_rename_habit_growthhabit_alter_growthhabit_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowerColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "flower_color",
                    models.CharField(blank=True, max_length=25, unique=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="flower_color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.flowercolor",
            ),
        ),
        migrations.DeleteModel(
            name="Color",
        ),
    ]
