# Generated by Django 5.1.3 on 2024-11-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0030_dormancy_seedlibrary_dormancy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seedstorage",
            name="seed_storage",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
