# Generated by Django 5.1.3 on 2025-06-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0030_flowercolor_alter_plantprofile_flower_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="beginner_friendly",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
