# Generated by Django 5.1.3 on 2025-06-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0031_plantprofile_beginner_friendly"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantprofile",
            name="soil_humidity_min",
        ),
        migrations.RemoveField(
            model_name="plantprofile",
            name="soil_humidity_max",
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="moisture_dry",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="moisture_medium",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="moisture_wet",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name="SoilHumidity",
        ),
    ]
