# Generated by Django 5.1.3 on 2024-11-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0031_alter_seedstorage_seed_storage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedPreparation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("seed_preparation", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
