# Generated by Django 5.1.3 on 2024-11-21 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0032_seedpreparation"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="seed_preparation",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to="project.seedpreparation"
            ),
        ),
    ]
