# Generated by Django 5.1.3 on 2025-06-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0032_remove_plantprofile_soil_humidity_min_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="spread_by_rhizome",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
