# Generated by Django 5.1.3 on 2025-06-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0033_plantprofile_spread_by_rhizome"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="dioecious",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
