# Generated by Django 5.1.3 on 2024-11-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0034_alter_onecultivar_one_cultivar"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="hyperlink",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
