# Generated by Django 5.1.3 on 2025-06-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0034_plantprofile_dioecious"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantprofile",
            name="min_height",
        ),
        migrations.RemoveField(
            model_name="plantprofile",
            name="min_width",
        ),
    ]
