# Generated by Django 5.1.3 on 2025-06-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0035_remove_plantprofile_min_height_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flowercolor",
            old_name="flower_color",
            new_name="bloom_color",
        ),
        migrations.RenameField(
            model_name="plantprofile",
            old_name="flower_color",
            new_name="bloom_color",
        ),
        migrations.RemoveField(
            model_name="plantprofile",
            name="size",
        ),
    ]
