# Generated by Django 5.1.3 on 2024-11-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0035_seedlibrary_hyperlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="label_link",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
