# Generated by Django 5.1.3 on 2024-11-21 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0036_seedlibrary_label_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seedlibrary",
            old_name="label_link",
            new_name="envelope_label_link",
        ),
    ]
