# Generated by Django 5.1.3 on 2025-06-26 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0036_rename_flower_color_flowercolor_bloom_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedEventTable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("event_table", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["event_table"],
            },
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="seed_event_table",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to="project.seedeventtable"
            ),
        ),
    ]
