# Generated by Django 5.1.3 on 2025-06-26 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0037_seedeventtable_plantprofile_seed_event_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seedeventtable",
            options={"ordering": ["seed_event_table"]},
        ),
        migrations.RenameField(
            model_name="seedeventtable",
            old_name="event_table",
            new_name="seed_event_table",
        ),
    ]
