# Generated by Django 5.1.3 on 2024-11-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0037_rename_label_link_seedlibrary_envelope_label_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="harvesting_video_link",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
