# Generated by Django 5.1.3 on 2024-11-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0038_seedlibrary_harvesting_video_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="seed_picture_link",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
