# Generated by Django 5.1.3 on 2025-06-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0038_alter_seedeventtable_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FlowerColor",
            new_name="BloomColor",
        ),
    ]
