# Generated by Django 5.1.3 on 2025-06-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0039_rename_flowercolor_bloomcolor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="boulevard_tolerant",
            new_name="boulevard_garden_tolerant",
        ),
    ]
