# Generated by Django 5.1.3 on 2024-11-21 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0040_seedlibrary_pods_seed_head_picture_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedStorageLabelInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("seed_storage_label_info", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="seedstorage",
            name="seed_storage",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="seed_storage_label_info",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to="project.seedstoragelabelinfo"
            ),
        ),
    ]
