# Generated by Django 5.1.3 on 2025-06-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0040_rename_boulevard_tolerant_plantprofile_boulevard_garden_tolerant"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="septic_tank_safe",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
