# Generated by Django 5.1.3 on 2025-06-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0041_plantprofile_septic_tank_safe"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="wetland_garden",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
