# Generated by Django 5.1.3 on 2024-11-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0041_seedstoragelabelinfo_alter_seedstorage_seed_storage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seedstorage",
            name="seed_storage",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
