# Generated by Django 5.1.3 on 2025-06-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0042_plantprofile_wetland_garden"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="grasp_candidate",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
