# Generated by Django 5.1.3 on 2024-11-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0042_alter_seedstorage_seed_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="notes",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
