# Generated by Django 5.1.3 on 2024-11-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0043_seedlibrary_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="germinate_easy",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
