# Generated by Django 5.1.3 on 2025-07-01 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0043_plantprofile_grasp_candidate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantprofile",
            name="url",
        ),
    ]
