# Generated by Django 5.1.3 on 2024-11-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0044_seedlibrary_germinate_easy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seedlibrary",
            name="notes",
            field=models.CharField(blank=True, max_length=450),
        ),
    ]
