# Generated by Django 5.1.3 on 2025-07-02 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0044_remove_plantprofile_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToxicityIndicator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("toxicity_indicator", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="toxicity_indicator",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to="project.toxicityindicator"
            ),
        ),
    ]
