# Generated by Django 5.1.3 on 2025-07-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0045_toxicityindicator_plantprofile_toxicity_indicator"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="grasp_candidate_notes",
            field=models.CharField(blank=True, max_length=450),
        ),
    ]
