# Generated by Django 5.1.3 on 2024-11-22 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0045_alter_seedlibrary_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RockGarden",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("rock_garden", models.BooleanField(blank=True, default=False)),
                (
                    "latin_name",
                    models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to="project.seedlibrary"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
