# Generated by Django 5.1.3 on 2025-07-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0046_plantprofile_grasp_candidate_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="toxicity_notes",
            new_name="toxicity_indicator_notes",
        ),
    ]
