# Generated by Django 5.1.3 on 2024-11-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0046_rockgarden"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="rock_garden",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name="RockGarden",
        ),
    ]
