# Generated by Django 5.1.3 on 2025-07-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0047_rename_toxicity_notes_plantprofile_toxicity_indicator_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="self_seeding",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
