# Generated by Django 5.1.3 on 2024-11-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0047_seedlibrary_rock_garden_delete_rockgarden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seedlibrary",
            name="rock_garden",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
