# Generated by Django 5.1.3 on 2025-07-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0048_plantprofile_self_seeding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantprofile",
            name="spreading_rate",
        ),
        migrations.DeleteModel(
            name="SpreadRate",
        ),
    ]
