# Generated by Django 5.1.3 on 2024-11-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0048_alter_seedlibrary_rock_garden"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="container_suitable",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="erosion_control",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="garden_edge",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="ground_cover",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="pond_edge",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="rain_garden",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="shoreline_rehab",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="wind_break_hedge",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="seedlibrary",
            name="woodland_garden",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
