# Generated by Django 5.1.3 on 2025-07-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0049_remove_plantprofile_spreading_rate_delete_spreadrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="does_not_spread",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
