# Generated by Django 5.1.3 on 2025-07-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0050_plantprofile_does_not_spread"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="has_image_profile",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
