# Generated by Django 5.1.3 on 2024-11-23 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0050_lighting_alter_seedlibrary_light_from"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seedlibrary",
            name="light_from",
        ),
    ]
