# Generated by Django 5.1.3 on 2025-07-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0051_plantprofile_has_image_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ButterflySpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latin_name",
                    models.CharField(blank=True, max_length=75, unique=True),
                ),
                ("english_name", models.CharField(blank=True, max_length=75)),
            ],
            options={
                "verbose_name_plural": "Butterfly Species",
                "ordering": ["latin_name"],
            },
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="moisture_dry",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Does the plant tolerate dry conditions?",
                null=True,
            ),
        ),
    ]
