# Generated by Django 5.1.3 on 2024-11-23 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0051_remove_seedlibrary_light_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="light_from",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to="project.lighting"
            ),
        ),
    ]
