# Generated by Django 5.1.3 on 2025-07-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0052_butterflyspecies_alter_plantprofile_moisture_dry"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="butterfly_host",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
