# Generated by Django 5.1.3 on 2024-11-23 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0053_alter_lighting_lighting_alter_seedlibrary_light_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seedlibrary",
            name="light_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="light_min",
                to="project.lighting",
            ),
        ),
        migrations.AlterField(
            model_name="seedlibrary",
            name="light_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="light_max",
                to="project.lighting",
            ),
        ),
    ]
