# Generated by Django 5.1.3 on 2025-07-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0053_plantprofile_butterfly_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="bee_host",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
