# Generated by Django 5.1.3 on 2024-11-23 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0054_alter_seedlibrary_light_from_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seedlibrary",
            name="light_to",
        ),
    ]
