# Generated by Django 5.1.3 on 2025-07-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0054_plantprofile_bee_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="butterflies",
            field=models.ManyToManyField(
                blank=True, related_name="plants", to="project.butterflyspecies"
            ),
        ),
    ]
