# Generated by Django 5.1.3 on 2025-07-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0055_plantprofile_butterflies"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="native_to_ottawa_region",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Is the plant native to the Ottawa region?",
                null=True,
            ),
        ),
    ]
