# Generated by Django 5.1.3 on 2024-11-23 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0056_alter_seedlibrary_light_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="light_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="light_to",
                to="project.lighting",
            ),
        ),
        migrations.AlterField(
            model_name="seedlibrary",
            name="light_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="light_from",
                to="project.lighting",
            ),
        ),
    ]
