# Generated by Django 5.1.3 on 2025-07-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0056_plantprofile_native_to_ottawa_region"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ViablityTest",
            new_name="ViabilityTest",
        ),
    ]
