# Generated by Django 5.1.3 on 2025-07-29 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0057_rename_viablitytest_viabilitytest"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ViabilityTest",
            new_name="SeedViabilityTest",
        ),
    ]
