# Generated by Django 5.1.3 on 2025-07-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0058_rename_viabilitytest_seedviabilitytest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seedviabilitytest",
            options={"ordering": ["seed_viability_test"]},
        ),
        migrations.RenameField(
            model_name="seedviabilitytest",
            old_name="viability_test",
            new_name="seed_viability_test",
        ),
    ]
