# Generated by Django 5.1.3 on 2024-11-26 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0059_alter_seedlibrary_soil_humidity_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seedlibrary",
            name="soil_humidity_max",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="soil_humidity_max",
                to="project.soilhumidity",
            ),
        ),
        migrations.AlterField(
            model_name="seedlibrary",
            name="soil_humidity_min",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="soil_humidity_min",
                to="project.soilhumidity",
            ),
        ),
    ]
