# Generated by Django 5.1.3 on 2025-07-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0059_alter_seedviabilitytest_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="viability_test",
            new_name="seed_viability_test",
        ),
    ]
