# Generated by Django 5.1.3 on 2025-07-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0060_rename_viability_test_plantprofile_seed_viability_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantprofile",
            name="seed_cleaning_notes",
        ),
        migrations.RemoveField(
            model_name="plantprofile",
            name="transplanting_notes",
        ),
    ]
