# Generated by Django 5.1.3 on 2025-08-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0061_remove_plantprofile_seed_cleaning_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="ecozone_prairie",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Is the plant native to the Prairie Ecozone?",
                null=True,
            ),
        ),
    ]
