# Generated by Django 5.1.3 on 2024-12-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0062_alter_seedlibrary_harvesting_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seedlibrary",
            name="bloom_end",
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="seedlibrary",
            name="bloom_start",
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
