# Generated by Django 5.1.3 on 2025-08-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0062_plantprofile_ecozone_prairie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ecozone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("ecozone", models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="plantprofile",
            name="ecozone_prairie",
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="ecozones",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ecozones where the plant thrives.",
                related_name="plants",
                to="project.ecozone",
            ),
        ),
    ]
