# Generated by Django 5.1.3 on 2025-08-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0063_ecozone_remove_plantprofile_ecozone_prairie_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="partial_sun",
            new_name="partial_shade",
        ),
    ]
