# Generated by Django 5.1.3 on 2025-08-10 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0064_rename_partial_sun_plantprofile_partial_shade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="partial_shade",
            new_name="part_shade",
        ),
    ]
