# Generated by Django 5.1.3 on 2024-12-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0064_alter_seedlibrary_bloom_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seedlibrary",
            name="harvesting_end",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="seedlibrary",
            name="harvesting_start",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default=0,
            ),
        ),
    ]
