# Generated by Django 5.1.3 on 2025-08-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0065_rename_partial_shade_plantprofile_part_shade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantprofile",
            name="pond_edge",
        ),
    ]
