# Generated by Django 5.1.3 on 2024-12-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0065_alter_seedlibrary_harvesting_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedlibrary",
            name="seed_availability",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
