# Generated by Django 5.1.3 on 2025-08-12 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0066_remove_plantprofile_pond_edge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantprofile",
            name="garden_edge",
        ),
    ]
