# Generated by Django 5.1.3 on 2025-08-12 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0067_remove_plantprofile_garden_edge"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="school_garden_suitable",
            new_name="school_garden",
        ),
    ]
