# Generated by Django 5.1.3 on 2024-12-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0067_color_habitat_seedlibrary_deer_tolerent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lighting",
            name="definition",
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
