# Generated by Django 5.1.3 on 2025-08-12 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0068_rename_school_garden_suitable_plantprofile_school_garden"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantprofile",
            name="wind_break_hedge",
        ),
    ]
