# Generated by Django 5.1.3 on 2025-08-12 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0069_remove_plantprofile_wind_break_hedge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantprofile",
            name="erosion_control",
        ),
    ]
