# Generated by Django 5.1.3 on 2024-12-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0070_rename_habitat_habit_rename_habitat_habit_habit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="color",
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
