# Generated by Django 5.1.3 on 2025-08-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0070_remove_plantprofile_erosion_control"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="cedar_hedge_replacement",
            new_name="hedge",
        ),
    ]
