# Generated by Django 5.1.3 on 2025-08-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0071_rename_cedar_hedge_replacement_plantprofile_hedge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantprofile",
            name="bee_friendly",
        ),
    ]
