# Generated by Django 5.1.3 on 2024-12-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0071_alter_color_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="habit",
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="lighting",
            name="lighting",
            field=models.CharField(blank=True, max_length=45, unique=True),
        ),
    ]
