# Generated by Django 5.1.3 on 2025-08-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0072_remove_plantprofile_bee_friendly"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="butterfly_friendly",
            new_name="pollinator_garden",
        ),
    ]
