# Generated by Django 5.1.3 on 2025-08-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0073_rename_butterfly_friendly_plantprofile_pollinator_garden"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
