# Generated by Django 5.1.3 on 2024-12-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0073_projectuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="SowingDepth",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("sowing_depth", models.CharField(blank=True, max_length=25)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
