# Generated by Django 5.1.3 on 2025-08-16 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0074_plantprofile_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObsoleteNames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("obsolete_name", models.CharField(blank=True, max_length=75)),
                (
                    "latin_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.plantprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
