# Generated by Django 5.1.3 on 2024-12-11 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0075_alter_seedlibrary_sowing_depth"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ["habit"]},
        ),
        migrations.AlterModelOptions(
            name="harvestingindicator",
            options={"ordering": ["harvesting_indicator"]},
        ),
        migrations.AlterModelOptions(
            name="harvestingmean",
            options={"ordering": ["harvesting_mean"]},
        ),
        migrations.AlterModelOptions(
            name="onecultivar",
            options={"ordering": ["one_cultivar"]},
        ),
        migrations.AlterModelOptions(
            name="packagingmeasure",
            options={"ordering": ["packaging_measure"]},
        ),
        migrations.AlterModelOptions(
            name="seedhead",
            options={"ordering": ["seed_head"]},
        ),
        migrations.AlterModelOptions(
            name="seedpreparation",
            options={"ordering": ["seed_preparation"]},
        ),
        migrations.AlterModelOptions(
            name="seedstoragelabelinfo",
            options={"ordering": ["seed_storage_label_info"]},
        ),
        migrations.AlterModelOptions(
            name="sowingdepth",
            options={"ordering": ["sowing_depth"]},
        ),
        migrations.AlterModelOptions(
            name="viablitytest",
            options={"ordering": ["viability_test"]},
        ),
    ]
