# Generated by Django 5.1.3 on 2025-08-16 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0075_obsoletenames"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="obsoletenames",
            name="latin_name",
        ),
        migrations.AddField(
            model_name="obsoletenames",
            name="plant_profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obsolete_names",
                to="project.plantprofile",
            ),
            preserve_default=False,
        ),
    ]
