# Generated by Django 5.1.3 on 2024-12-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0076_alter_habit_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SeedLibrary",
            new_name="PlantProfile",
        ),
    ]
