# Generated by Django 5.1.3 on 2025-08-22 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0076_remove_obsoletenames_latin_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantPairWellWith",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plant_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="well_with",
                        to="project.plantprofile",
                    ),
                ),
                (
                    "well_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="well_with_pairings",
                        to="project.plantprofile",
                    ),
                ),
            ],
        ),
    ]
