# Generated by Django 5.1.3 on 2025-08-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0077_plantpairwellwith"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantCompanion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "companion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companion",
                        to="project.plantprofile",
                    ),
                ),
                (
                    "plant_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant",
                        to="project.plantprofile",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PlantPairWellWith",
        ),
    ]
