# Generated by Django 5.1.3 on 2024-12-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0077_rename_seedlibrary_plantprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantprofile",
            name="max_height",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
