# Generated by Django 5.1.3 on 2024-12-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0078_alter_plantprofile_max_height"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantprofile",
            name="min_height",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
