# Generated by Django 5.1.3 on 2025-08-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0078_plantcompanion_delete_plantpairwellwith"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plantcompanion",
            options={
                "ordering": ["plant_profile__latin_name", "companion__latin_name"]
            },
        ),
        migrations.AlterUniqueTogether(
            name="plantcompanion",
            unique_together={("plant_profile", "companion")},
        ),
        migrations.AddConstraint(
            model_name="plantcompanion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("plant_profile", models.F("companion")), _negated=True
                ),
                name="different_plants",
            ),
        ),
    ]
