# Generated by Django 5.1.3 on 2025-08-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0079_alter_plantcompanion_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeeSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latin_name",
                    models.CharField(blank=True, max_length=75, unique=True),
                ),
            ],
            options={
                "verbose_name_plural": "Bee Species",
                "ordering": ["latin_name"],
            },
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="bees",
            field=models.ManyToManyField(
                blank=True, related_name="plants", to="project.beespecies"
            ),
        ),
    ]
