# Generated by Django 5.1.3 on 2025-08-24 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0080_beespecies_plantprofile_bees"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantComplementary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "complement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complement",
                        to="project.plantprofile",
                    ),
                ),
                (
                    "plant_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant",
                        to="project.plantprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["plant_profile__latin_name", "complement__latin_name"],
            },
        ),
        migrations.DeleteModel(
            name="PlantCompanion",
        ),
        migrations.AddConstraint(
            model_name="plantcomplementary",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("plant_profile", models.F("complement")), _negated=True
                ),
                name="different_plants",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plantcomplementary",
            unique_together={("plant_profile", "complement")},
        ),
    ]
