# Generated by Django 5.1.3 on 2024-12-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0080_alter_plantprofile_stratification_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantprofile",
            name="latin_name",
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
