# Generated by Django 5.1.3 on 2024-12-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0081_alter_plantprofile_latin_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plantprofile",
            options={"ordering": ["latin_name"]},
        ),
    ]
