# Generated by Django 5.1.3 on 2025-08-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0081_plantcomplementary_delete_plantcompanion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="ephemeral",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
