# Generated by Django 5.1.3 on 2025-08-28 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0082_plantprofile_ephemeral"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="ephemeral",
            new_name="spring_ephemeral",
        ),
    ]
