# Generated by Django 5.1.3 on 2025-09-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0084_alter_onecultivar_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="cause_dermatitis",
            new_name="cause_skin_rashes",
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="remove_non_seed_material",
            field=models.BooleanField(default=False),
        ),
    ]
