# Generated by Django 5.1.3 on 2025-09-08 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0085_rename_cause_dermatitis_plantprofile_cause_skin_rashes_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantprofile",
            name="sowing_period",
        ),
    ]
