# Generated by Django 5.1.3 on 2025-09-08 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0086_remove_plantprofile_sowing_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantprofile",
            name="sharing_priority",
        ),
        migrations.DeleteModel(
            name="SharingPriority",
        ),
    ]
