# Generated by Django 5.1.3 on 2025-09-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0087_remove_plantprofile_sharing_priority_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plantprofile",
            name="dormancy",
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="double_dormancy",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Dormancy",
        ),
    ]
