# Generated by Django 5.1.3 on 2025-09-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0088_remove_plantprofile_dormancy_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="foot_traffic_tolerant",
            new_name="foot_traffic_tolerance_light",
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="foot_traffic_tolerance_medium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="foot_traffic_tolerance_no",
            field=models.BooleanField(default=False),
        ),
    ]
