# Generated by Django 5.1.3 on 2025-09-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0089_rename_foot_traffic_tolerant_plantprofile_foot_traffic_tolerance_light_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="show_bees_supported_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="show_butterflies_supported_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="show_complementary_plants_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="show_ecological_benefits_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="show_ecozones_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="show_env_requirements_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="show_gardener_friendly_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="show_harvesting_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="show_inaturalist_link_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="show_landscape_uses_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="show_obsolete_names_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="show_sowing_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="show_tolerates_info",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="show_vascan_map_info",
            field=models.BooleanField(default=True),
        ),
    ]
