# Generated by Django 5.1.3 on 2025-09-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0090_plantprofile_show_bees_supported_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="is_accepted",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="not_accepted_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
