# Generated by Django 5.1.3 on 2025-09-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0091_plantprofile_is_accepted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="starter_pack_dry",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="starter_pack_full_sun",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="starter_pack_part_shade",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="plantimage",
            name="image",
            field=models.ImageField(upload_to="project/images/plants"),
        ),
    ]
