# Generated by Django 5.1.3 on 2025-09-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0092_plantprofile_starter_pack_dry_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="starter_pack_dry",
            new_name="starter_pack_shade",
        ),
        migrations.RenameField(
            model_name="plantprofile",
            old_name="starter_pack_full_sun",
            new_name="starter_pack_sun_dry",
        ),
        migrations.RenameField(
            model_name="plantprofile",
            old_name="starter_pack_part_shade",
            new_name="starter_pack_sun_wet",
        ),
    ]
