# Generated by Django 5.1.3 on 2025-10-02 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0093_rename_starter_pack_dry_plantprofile_starter_pack_shade_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plantimage",
            options={"ordering": ["plant_profile__latin_name", "title"]},
        ),
        migrations.AlterField(
            model_name="plantimage",
            name="plant_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="project.plantprofile",
                unique=True,
            ),
        ),
    ]
