# Generated by Django 5.1.3 on 2025-10-02 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0094_alter_plantimage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantimage",
            name="plant_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="project.plantprofile",
            ),
        ),
    ]
