# Generated by Django 5.1.3 on 2025-10-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0095_alter_plantimage_plant_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantimage",
            name="image",
            field=models.ImageField(unique=True, upload_to="project/images/plants"),
        ),
    ]
