# Generated by Django 5.1.3 on 2025-10-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0096_alter_plantimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantimage",
            name="image",
            field=models.ImageField(upload_to="project/images/plants"),
        ),
    ]
