# Generated by Django 5.1.3 on 2025-10-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0097_alter_plantimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
    ]
