# Generated by Django 5.1.3 on 2025-10-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0098_plantprofile_is_draft"),
    ]

    operations = [
        migrations.CreateModel(
            name="StratificationDuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "stratification_duration",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
