# Generated by Django 5.1.3 on 2025-10-08 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0099_stratificationduration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantprofile",
            name="stratification_duration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.stratificationduration",
            ),
        ),
    ]
