# Generated by Django 5.1.3 on 2025-10-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0100_alter_plantprofile_stratification_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stratificationduration",
            name="stratification_duration",
            field=models.SmallIntegerField(
                blank=True, default=0, null=True, unique=True
            ),
        ),
    ]
