# Generated by Django 5.1.3 on 2025-10-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0101_alter_stratificationduration_stratification_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="distribution_in_AB",
            field=models.CharField(default="", max_length=1, verbose_name="AB"),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="distribution_in_BC",
            field=models.CharField(default="", max_length=1, verbose_name="BC"),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="distribution_in_MB",
            field=models.CharField(default="", max_length=1, verbose_name="MB"),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="distribution_in_NB",
            field=models.CharField(default="", max_length=1, verbose_name="NB"),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="distribution_in_NL",
            field=models.CharField(default="", max_length=1, verbose_name="NL"),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="distribution_in_NS",
            field=models.CharField(default="", max_length=1, verbose_name="NS"),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="distribution_in_NT",
            field=models.CharField(default="", max_length=1, verbose_name="NT"),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="distribution_in_NU",
            field=models.CharField(default="", max_length=1, verbose_name="NU"),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="distribution_in_ON",
            field=models.CharField(default="", max_length=1, verbose_name="ON"),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="distribution_in_PE",
            field=models.CharField(default="", max_length=1, verbose_name="PE"),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="distribution_in_QC",
            field=models.CharField(default="", max_length=1, verbose_name="QC"),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="distribution_in_SK",
            field=models.CharField(default="", max_length=1, verbose_name="SK"),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="distribution_in_YT",
            field=models.CharField(default="", max_length=1, verbose_name="YT"),
        ),
    ]
