# Generated by Django 5.1.3 on 2025-10-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0102_plantprofile_distribution_in_ab_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantlifespan",
            name="definition",
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
