# Generated by Django 5.1.3 on 2025-10-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0103_plantlifespan_definition"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="has_recall",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="recall_reason",
            field=models.CharField(default=False, max_length=255),
        ),
    ]
