# Generated by Django 5.1.3 on 2025-10-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0104_plantprofile_has_recall_plantprofile_recall_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantprofile",
            name="recall_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
