# Generated by Django 5.1.3 on 2025-10-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0105_alter_plantprofile_recall_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantprofile",
            name="is_native_to_AB",
            field=models.BooleanField(default=False, verbose_name="AB"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="is_native_to_BC",
            field=models.BooleanField(default=False, verbose_name="BC"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="is_native_to_MB",
            field=models.BooleanField(default=False, verbose_name="MB"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="is_native_to_NB",
            field=models.BooleanField(default=False, verbose_name="NB"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="is_native_to_NL",
            field=models.BooleanField(default=False, verbose_name="NL"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="is_native_to_NS",
            field=models.BooleanField(default=False, verbose_name="NS"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="is_native_to_NT",
            field=models.BooleanField(default=False, verbose_name="NT"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="is_native_to_NU",
            field=models.BooleanField(default=False, verbose_name="NU"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="is_native_to_ON",
            field=models.BooleanField(default=False, verbose_name="ON"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="is_native_to_PE",
            field=models.BooleanField(default=False, verbose_name="PE"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="is_native_to_QC",
            field=models.BooleanField(default=False, verbose_name="QC"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="is_native_to_SK",
            field=models.BooleanField(default=False, verbose_name="SK"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="is_native_to_YT",
            field=models.BooleanField(default=False, verbose_name="YT"),
        ),
    ]
