# Generated by Django 5.1.3 on 2025-10-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0106_alter_plantprofile_is_native_to_ab_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="has_recall",
            new_name="has_notice",
        ),
        migrations.RenameField(
            model_name="plantprofile",
            old_name="recall_reason",
            new_name="notice_detail",
        ),
    ]
