# Generated by Django 5.1.3 on 2025-10-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0107_rename_has_recall_plantprofile_has_notice_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BloomColor",
            new_name="BloomColour",
        ),
        migrations.RenameField(
            model_name="bloomcolour",
            old_name="bloom_color",
            new_name="bloom_colour",
        ),
        migrations.RenameField(
            model_name="plantprofile",
            old_name="bloom_color",
            new_name="bloom_colour",
        ),
    ]
