# Generated by Django 5.1.3 on 2025-10-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0108_rename_bloomcolor_bloomcolour_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onecultivar",
            options={"ordering": ["one_cultivar"]},
        ),
        migrations.RenameField(
            model_name="onecultivar",
            old_name="on_cultivar",
            new_name="one_cultivar",
        ),
        migrations.RenameField(
            model_name="plantprofile",
            old_name="on_cultivar",
            new_name="one_cultivar",
        ),
        migrations.AlterField(
            model_name="plantlifespan",
            name="lifespan",
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
