# Generated by Django 5.1.3 on 2025-10-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0109_alter_onecultivar_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantprofile",
            old_name="foot_traffic_tolerance_light",
            new_name="foot_traffic_tolerant",
        ),
        migrations.RemoveField(
            model_name="plantprofile",
            name="foot_traffic_tolerance_medium",
        ),
        migrations.RemoveField(
            model_name="plantprofile",
            name="foot_traffic_tolerance_no",
        ),
    ]
