# Generated by Django 5.1.3 on 2025-10-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0110_rename_foot_traffic_tolerance_light_plantprofile_foot_traffic_tolerant_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NonNativeSpecies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latin_name",
                    models.CharField(blank=True, max_length=75, unique=True),
                ),
                ("english_name", models.CharField(blank=True, max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name="plantprofile",
            name="substitute_for_non_native",
            field=models.ManyToManyField(
                blank=True,
                related_name="native_alternatives",
                to="project.nonnativespecies",
            ),
        ),
    ]
