# Generated by Django 5.1.3 on 2025-10-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0111_nonnativespecies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="show_alternative_to_info",
            field=models.BooleanField(default=True),
        ),
    ]
