# Generated by Django 5.1.3 on 2025-10-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0112_plantprofile_show_alternative_to_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonnativespecies",
            name="latin_name",
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterUniqueTogether(
            name="nonnativespecies",
            unique_together={("latin_name", "english_name")},
        ),
    ]
