# Generated by Django 5.2.7 on 2025-11-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0113_alter_nonnativespecies_latin_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="is_needed",
            field=models.BooleanField(default=False),
        ),
    ]
