# Generated by Django 5.2.7 on 2025-12-04 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0114_plantprofile_is_needed"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloomcolour",
            name="bloom_colour_fr",
            field=models.CharField(
                blank=True, max_length=25, verbose_name="Bloom Colour (French)"
            ),
        ),
        migrations.AlterField(
            model_name="beespecies",
            name="latin_name",
            field=models.CharField(
                blank=True, max_length=75, unique=True, verbose_name="Latin Name"
            ),
        ),
        migrations.AlterField(
            model_name="bloomcolour",
            name="bloom_colour",
            field=models.CharField(
                blank=True, max_length=25, unique=True, verbose_name="Bloom Colour"
            ),
        ),
        migrations.AlterField(
            model_name="butterflyspecies",
            name="english_name",
            field=models.CharField(
                blank=True, max_length=75, verbose_name="English Name"
            ),
        ),
        migrations.AlterField(
            model_name="butterflyspecies",
            name="latin_name",
            field=models.CharField(
                blank=True, max_length=75, unique=True, verbose_name="Latin Name"
            ),
        ),
        migrations.AlterField(
            model_name="conservationstatus",
            name="conservation_status",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Conservation Status"
            ),
        ),
        migrations.AlterField(
            model_name="ecozone",
            name="ecozone",
            field=models.CharField(
                blank=True, max_length=100, unique=True, verbose_name="Ecozone"
            ),
        ),
        migrations.AlterField(
            model_name="growthhabit",
            name="growth_habit",
            field=models.CharField(
                blank=True, max_length=30, unique=True, verbose_name="Growth Habit"
            ),
        ),
        migrations.AlterField(
            model_name="harvestingindicator",
            name="harvesting_indicator",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Harvesting Indicator"
            ),
        ),
        migrations.AlterField(
            model_name="harvestingmean",
            name="harvesting_mean",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Harvesting"
            ),
        ),
        migrations.AlterField(
            model_name="lighting",
            name="definition",
            field=models.CharField(
                blank=True, max_length=75, verbose_name="Definition"
            ),
        ),
        migrations.AlterField(
            model_name="lighting",
            name="lighting",
            field=models.CharField(
                blank=True, max_length=45, unique=True, verbose_name="Lighting"
            ),
        ),
        migrations.AlterField(
            model_name="nonnativespecies",
            name="english_name",
            field=models.CharField(
                blank=True, max_length=75, verbose_name="English Name"
            ),
        ),
        migrations.AlterField(
            model_name="nonnativespecies",
            name="latin_name",
            field=models.CharField(
                blank=True, max_length=75, verbose_name="Latin Name"
            ),
        ),
        migrations.AlterField(
            model_name="obsoletenames",
            name="obsolete_name",
            field=models.CharField(
                blank=True, max_length=75, verbose_name="Obsolete Name"
            ),
        ),
        migrations.AlterField(
            model_name="obsoletenames",
            name="plant_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obsolete_names",
                to="project.plantprofile",
                verbose_name="Plant Profile",
            ),
        ),
        migrations.AlterField(
            model_name="onecultivar",
            name="one_cultivar",
            field=models.CharField(blank=True, max_length=125, verbose_name="Cultivar"),
        ),
        migrations.AlterField(
            model_name="packagingmeasure",
            name="packaging_measure",
            field=models.CharField(
                blank=True, max_length=35, verbose_name="Packaging Measure"
            ),
        ),
        migrations.AlterField(
            model_name="plantcollection",
            name="details",
            field=models.CharField(blank=True, max_length=125, verbose_name="Details"),
        ),
        migrations.AlterField(
            model_name="plantcollection",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="plantcollection",
            name="plants",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.plantprofile",
                verbose_name="Plants",
            ),
        ),
        migrations.AlterField(
            model_name="plantcomplementary",
            name="complement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complements",
                to="project.plantprofile",
                verbose_name="Complement",
            ),
        ),
        migrations.AlterField(
            model_name="plantcomplementary",
            name="plant_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plant",
                to="project.plantprofile",
                verbose_name="Plant Profile",
            ),
        ),
        migrations.AlterField(
            model_name="plantimage",
            name="morphology_aspect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project.plantmorphology",
                verbose_name="Morphology Aspect",
            ),
        ),
        migrations.AlterField(
            model_name="plantimage",
            name="photo_author",
            field=models.CharField(max_length=125, verbose_name="Author"),
        ),
        migrations.AlterField(
            model_name="plantimage",
            name="photo_date",
            field=models.DateField(verbose_name="Photo Date"),
        ),
        migrations.AlterField(
            model_name="plantimage",
            name="plant_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="project.plantprofile",
                verbose_name="Plant Profile",
            ),
        ),
        migrations.AlterField(
            model_name="plantimage",
            name="title",
            field=models.CharField(max_length=125, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="plantlifespan",
            name="definition",
            field=models.CharField(
                blank=True, max_length=75, verbose_name="Definition"
            ),
        ),
        migrations.AlterField(
            model_name="plantlifespan",
            name="lifespan",
            field=models.CharField(
                blank=True, max_length=15, unique=True, verbose_name="Lifespan"
            ),
        ),
        migrations.AlterField(
            model_name="plantmorphology",
            name="element",
            field=models.CharField(
                blank=True, max_length=75, unique=True, verbose_name="Element"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="accepting_seed",
            field=models.BooleanField(default=False, verbose_name="Accepting Seed"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="acidic_soil_tolerant",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Acidic Soil Tolerant",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="alternative_to_notes",
            field=models.CharField(
                blank=True, max_length=450, verbose_name="Alternative To Notes"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="bee_host",
            field=models.BooleanField(default=False, verbose_name="Bee Host"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="bees",
            field=models.ManyToManyField(
                blank=True,
                related_name="plants",
                to="project.beespecies",
                verbose_name="Bees",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="beginner_friendly",
            field=models.BooleanField(default=False, verbose_name="Beginner Friendly"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="bird_friendly",
            field=models.BooleanField(default=False, verbose_name="Bird Friendly"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="bloom_colour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.bloomcolour",
                verbose_name="Bloom Colour",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="bloom_end",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default=0,
                verbose_name="Bloom End",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="bloom_start",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default=0,
                verbose_name="Bloom Start",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="boulevard_garden_tolerant",
            field=models.BooleanField(
                default=False, verbose_name="Boulevard Garden Tolerant"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="butterflies",
            field=models.ManyToManyField(
                blank=True,
                related_name="plants",
                to="project.butterflyspecies",
                verbose_name="Butterflies",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="butterfly_host",
            field=models.BooleanField(default=False, verbose_name="Butterfly Host"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="cause_skin_rashes",
            field=models.BooleanField(default=False, verbose_name="Cause Skin Rashes"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="conservation_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.conservationstatus",
                verbose_name="Conservation Status",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="container_suitable",
            field=models.BooleanField(default=False, verbose_name="Container Suitable"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="deer_tolerant",
            field=models.BooleanField(default=False, verbose_name="Deer Tolerant"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="dioecious",
            field=models.BooleanField(default=False, verbose_name="Dioecious"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="does_not_spread",
            field=models.BooleanField(default=False, verbose_name="Does Not Spread"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="double_dormancy",
            field=models.BooleanField(default=False, verbose_name="Double Dormancy"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="drought_tolerant",
            field=models.BooleanField(default=False, verbose_name="Drought Tolerant"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="easy_to_contain",
            field=models.BooleanField(default=False, verbose_name="Easy to Contain"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="english_name",
            field=models.CharField(
                blank=True, max_length=75, verbose_name="English Name"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="envelope_label_link",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Envelope Label Link"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="foot_traffic_tolerant",
            field=models.BooleanField(
                default=False, verbose_name="Foot Traffic Tolerant"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="french_name",
            field=models.CharField(
                blank=True, max_length=75, verbose_name="French Name"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="full_shade",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Full Shade"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="full_sun",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Full Sun"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="germinate_easy",
            field=models.BooleanField(default=False, verbose_name="Germinate Easy"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="grasp_candidate",
            field=models.BooleanField(default=False, verbose_name="GRASP Candidate"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="grasp_candidate_notes",
            field=models.CharField(
                blank=True, max_length=450, verbose_name="GRASP Candidate Notes"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="ground_cover",
            field=models.BooleanField(default=False, verbose_name="Ground Cover"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="growth_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.growthhabit",
                verbose_name="Growth Habit",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="harvesting_indicator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.harvestingindicator",
                verbose_name="Harvesting Indicator",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="harvesting_mean",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.harvestingmean",
                verbose_name="Harvesting",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="harvesting_notes",
            field=models.CharField(
                blank=True, max_length=450, verbose_name="Harvesting Notes"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="harvesting_start",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                default=0,
                verbose_name="Harvesting Start",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="harvesting_video_link",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Harvesting Video Link"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="has_notice",
            field=models.BooleanField(default=False, verbose_name="Has Notice"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="hedge",
            field=models.BooleanField(default=False, verbose_name="Hedge"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="hummingbird_friendly",
            field=models.BooleanField(
                default=False, verbose_name="Hummingbird Friendly"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="inaturalist_taxon",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="iNaturalist Taxon"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="is_accepted",
            field=models.BooleanField(default=True, verbose_name="Is Accepted"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="is_draft",
            field=models.BooleanField(default=True, verbose_name="Is Draft"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="is_needed",
            field=models.BooleanField(default=False, verbose_name="Is Needed"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="juglone_tolerant",
            field=models.BooleanField(default=False, verbose_name="Juglone Tolerant"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="keystones_species",
            field=models.BooleanField(default=False, verbose_name="Keystones Species"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="latin_name",
            field=models.CharField(
                max_length=75, unique=True, verbose_name="Latin Name"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="limestone_tolerant",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Limestone Tolerant"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="moisture_dry",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Does the plant tolerate dry conditions?",
                null=True,
                verbose_name="Moisture Dry",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="moisture_medium",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Moisture Medium"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="moisture_wet",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Moisture Wet"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="nitrogen_fixer",
            field=models.BooleanField(default=False, verbose_name="Nitrogen Fixer"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="not_accepted_reason",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Not Accepted Reason"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="notes",
            field=models.CharField(blank=True, max_length=450, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="notice_detail",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Notice Detail"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="one_cultivar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.onecultivar",
                verbose_name="Cultivar",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="packaging_measure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.packagingmeasure",
                verbose_name="Packaging Measure",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="part_shade",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Part Shade"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="pollinator_garden",
            field=models.BooleanField(default=False, verbose_name="Pollinator Garden"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="produces_burs",
            field=models.BooleanField(default=False, verbose_name="Produces Burs"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="rabbit_tolerant",
            field=models.BooleanField(default=False, verbose_name="Rabbit Tolerant"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="rain_garden",
            field=models.BooleanField(default=False, verbose_name="Rain Garden"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="rock_garden",
            field=models.BooleanField(default=False, verbose_name="Rock Garden"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="salt_tolerant",
            field=models.BooleanField(default=False, verbose_name="Salt Tolerant"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="sand_tolerant",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Sand Tolerant"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="school_garden",
            field=models.BooleanField(default=False, verbose_name="School Garden"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="seed_availability",
            field=models.BooleanField(default=False, verbose_name="Seed Availability"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="seed_event_table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.seedeventtable",
                verbose_name="Seed Event Table",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="seed_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.seedhead",
                verbose_name="Seed Head",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="seed_preparation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.seedpreparation",
                verbose_name="Seed Preparation",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="seed_storage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.seedstorage",
                verbose_name="Seed Storage",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="seed_storage_label_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.seedstoragelabelinfo",
                verbose_name="Seed Storage Label Info",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="seed_viability_test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.seedviabilitytest",
                verbose_name="Seed Viability Test",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="self_seeding",
            field=models.BooleanField(default=False, verbose_name="Self Seeding"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="septic_tank_safe",
            field=models.BooleanField(default=False, verbose_name="Septic Tank Safe"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="shoreline_rehab",
            field=models.BooleanField(default=False, verbose_name="Shoreline Rehab"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="show_alternative_to_info",
            field=models.BooleanField(
                default=True, verbose_name="Show Alternative To Information"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="show_bees_supported_info",
            field=models.BooleanField(
                default=True, verbose_name="Show Bees Supported Information"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="show_butterflies_supported_info",
            field=models.BooleanField(
                default=True, verbose_name="Show Butterflies Supported Information"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="show_complementary_plants_info",
            field=models.BooleanField(
                default=True, verbose_name="Show Complementary Plants Information"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="show_ecological_benefits_info",
            field=models.BooleanField(
                default=True, verbose_name="Show Ecological Benefits Information"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="show_ecozones_info",
            field=models.BooleanField(
                default=True, verbose_name="Show Ecozones Information"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="show_env_requirements_info",
            field=models.BooleanField(
                default=True, verbose_name="Show Environmental Requirements Information"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="show_gardener_friendly_info",
            field=models.BooleanField(
                default=True, verbose_name="Show Gardener Friendly Information"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="show_harvesting_info",
            field=models.BooleanField(
                default=True, verbose_name="Show Harvesting Information"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="show_inaturalist_link_info",
            field=models.BooleanField(
                default=True, verbose_name="Show iNaturalist Link Information"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="show_landscape_uses_info",
            field=models.BooleanField(
                default=True, verbose_name="Show Landscape Uses Information"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="show_obsolete_names_info",
            field=models.BooleanField(
                default=True, verbose_name="Show Obsolete Names Information"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="show_sowing_info",
            field=models.BooleanField(
                default=True, verbose_name="Show Sowing Information"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="show_tolerates_info",
            field=models.BooleanField(
                default=True, verbose_name="Show Tolerates Information"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="show_vascan_map_info",
            field=models.BooleanField(
                default=True, verbose_name="Show Vascan Map Information"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="sowing_depth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.sowingdepth",
                verbose_name="Sowing Depth",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="sowing_label_instructions",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Sowing Label Instructions"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="sowing_notes",
            field=models.CharField(
                blank=True, max_length=450, verbose_name="Sowing Notes"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="spread_by_rhizome",
            field=models.BooleanField(default=False, verbose_name="Spread by Rhizome"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="spring_ephemeral",
            field=models.BooleanField(default=False, verbose_name="Spring Ephemeral"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="starter_pack_shade",
            field=models.BooleanField(default=False, verbose_name="Starter Pack Shade"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="starter_pack_sun_dry",
            field=models.BooleanField(
                default=False, verbose_name="Starter Pack Sun Dry"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="starter_pack_sun_wet",
            field=models.BooleanField(
                default=False, verbose_name="Starter Pack Sun Wet"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="stratification_detail",
            field=models.CharField(
                blank=True, max_length=55, verbose_name="Stratification Detail"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="stratification_duration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.stratificationduration",
                verbose_name="Stratification Duration",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="substitute_for_non_native",
            field=models.ManyToManyField(
                blank=True,
                related_name="native_alternatives",
                to="project.nonnativespecies",
                verbose_name="Substitute for Non Native",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="taxon",
            field=models.CharField(blank=True, max_length=5, verbose_name="Taxon"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="toxicity_indicator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="project.toxicityindicator",
                verbose_name="Toxicity Indicator",
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="transplantation_tolerant",
            field=models.BooleanField(
                default=False, verbose_name="Transplantation Tolerant"
            ),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="wetland_garden",
            field=models.BooleanField(default=False, verbose_name="Wetland Garden"),
        ),
        migrations.AlterField(
            model_name="plantprofile",
            name="woodland_garden",
            field=models.BooleanField(default=False, verbose_name="Woodland Garden"),
        ),
        migrations.AlterField(
            model_name="projectuser",
            name="plants",
            field=models.ManyToManyField(
                through="project.PlantCollection",
                to="project.plantprofile",
                verbose_name="Plants",
            ),
        ),
        migrations.AlterField(
            model_name="seedeventtable",
            name="seed_event_table",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Seed Event Table"
            ),
        ),
        migrations.AlterField(
            model_name="seedhead",
            name="seed_head",
            field=models.CharField(blank=True, max_length=20, verbose_name="Seed Head"),
        ),
        migrations.AlterField(
            model_name="seedpreparation",
            name="seed_preparation",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Seed Preparation"
            ),
        ),
        migrations.AlterField(
            model_name="seedstorage",
            name="seed_storage",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Seed Storage"
            ),
        ),
        migrations.AlterField(
            model_name="seedstoragelabelinfo",
            name="seed_storage_label_info",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Seed Storage Label Info"
            ),
        ),
        migrations.AlterField(
            model_name="seedviabilitytest",
            name="seed_viability_test",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Seed Viability Test"
            ),
        ),
        migrations.AlterField(
            model_name="sowingdepth",
            name="sowing_depth",
            field=models.CharField(
                blank=True, max_length=25, verbose_name="Sowing Depth"
            ),
        ),
        migrations.AlterField(
            model_name="stratificationduration",
            name="stratification_duration",
            field=models.SmallIntegerField(
                blank=True,
                default=0,
                null=True,
                unique=True,
                verbose_name="Stratification Duration",
            ),
        ),
        migrations.AlterField(
            model_name="toxicityindicator",
            name="toxicity_indicator",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Toxicity Indicator"
            ),
        ),
    ]
