# Generated by Django 5.2.7 on 2025-12-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0115_bloomcolour_bloom_colour_fr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloomcolour",
            name="bloom_colour_fr",
        ),
    ]
