# Generated by Django 5.2.7 on 2025-12-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0116_remove_bloomcolour_bloom_colour_fr"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloomcolour",
            name="bloom_colour_en",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                unique=True,
                verbose_name="Bloom Colour",
            ),
        ),
        migrations.AddField(
            model_name="bloomcolour",
            name="bloom_colour_fr",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                unique=True,
                verbose_name="Bloom Colour",
            ),
        ),
    ]
