# Generated by Django 5.2.7 on 2025-12-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0117_bloomcolour_bloom_colour_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="butterflyspecies",
            name="english_name_en",
            field=models.CharField(
                blank=True, max_length=75, null=True, verbose_name="English Name"
            ),
        ),
        migrations.AddField(
            model_name="butterflyspecies",
            name="english_name_fr",
            field=models.CharField(
                blank=True, max_length=75, null=True, verbose_name="English Name"
            ),
        ),
        migrations.AddField(
            model_name="butterflyspecies",
            name="latin_name_en",
            field=models.CharField(
                blank=True,
                max_length=75,
                null=True,
                unique=True,
                verbose_name="Latin Name",
            ),
        ),
        migrations.AddField(
            model_name="butterflyspecies",
            name="latin_name_fr",
            field=models.CharField(
                blank=True,
                max_length=75,
                null=True,
                unique=True,
                verbose_name="Latin Name",
            ),
        ),
    ]
