# Generated by Django 5.2.7 on 2025-12-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0118_butterflyspecies_english_name_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="butterflyspecies",
            name="latin_name_en",
        ),
        migrations.RemoveField(
            model_name="butterflyspecies",
            name="latin_name_fr",
        ),
    ]
