# Generated by Django 5.2.7 on 2025-12-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0119_remove_butterflyspecies_latin_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conservationstatus",
            name="conservation_status_en",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Conservation Status"
            ),
        ),
        migrations.AddField(
            model_name="conservationstatus",
            name="conservation_status_fr",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Conservation Status"
            ),
        ),
    ]
