# Generated by Django 5.2.7 on 2025-12-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0120_conservationstatus_conservation_status_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="growthhabit",
            name="growth_habit_en",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Growth Habit",
            ),
        ),
        migrations.AddField(
            model_name="growthhabit",
            name="growth_habit_fr",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Growth Habit",
            ),
        ),
    ]
