# Generated by Django 5.2.7 on 2025-12-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0121_growthhabit_growth_habit_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="harvestingindicator",
            name="harvesting_indicator_en",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Harvesting Indicator",
            ),
        ),
        migrations.AddField(
            model_name="harvestingindicator",
            name="harvesting_indicator_fr",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Harvesting Indicator",
            ),
        ),
    ]
