# Generated by Django 5.2.7 on 2025-12-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0122_harvestingindicator_harvesting_indicator_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="harvestingmean",
            name="harvesting_mean_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Harvesting"
            ),
        ),
        migrations.AddField(
            model_name="harvestingmean",
            name="harvesting_mean_fr",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Harvesting"
            ),
        ),
    ]
