# Generated by Django 5.2.7 on 2025-12-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0123_harvestingmean_harvesting_mean_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecozone",
            name="ecozone_en",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Ecozone",
            ),
        ),
        migrations.AddField(
            model_name="ecozone",
            name="ecozone_fr",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Ecozone",
            ),
        ),
        migrations.AddField(
            model_name="onecultivar",
            name="one_cultivar_en",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="Cultivar"
            ),
        ),
        migrations.AddField(
            model_name="onecultivar",
            name="one_cultivar_fr",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="Cultivar"
            ),
        ),
        migrations.AddField(
            model_name="packagingmeasure",
            name="packaging_measure_en",
            field=models.CharField(
                blank=True, max_length=35, null=True, verbose_name="Packaging Measure"
            ),
        ),
        migrations.AddField(
            model_name="packagingmeasure",
            name="packaging_measure_fr",
            field=models.CharField(
                blank=True, max_length=35, null=True, verbose_name="Packaging Measure"
            ),
        ),
        migrations.AddField(
            model_name="plantlifespan",
            name="definition_en",
            field=models.CharField(
                blank=True, max_length=75, null=True, verbose_name="Definition"
            ),
        ),
        migrations.AddField(
            model_name="plantlifespan",
            name="definition_fr",
            field=models.CharField(
                blank=True, max_length=75, null=True, verbose_name="Definition"
            ),
        ),
        migrations.AddField(
            model_name="plantlifespan",
            name="lifespan_en",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                verbose_name="Lifespan",
            ),
        ),
        migrations.AddField(
            model_name="plantlifespan",
            name="lifespan_fr",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                verbose_name="Lifespan",
            ),
        ),
        migrations.AddField(
            model_name="plantmorphology",
            name="element_en",
            field=models.CharField(
                blank=True,
                max_length=75,
                null=True,
                unique=True,
                verbose_name="Element",
            ),
        ),
        migrations.AddField(
            model_name="plantmorphology",
            name="element_fr",
            field=models.CharField(
                blank=True,
                max_length=75,
                null=True,
                unique=True,
                verbose_name="Element",
            ),
        ),
        migrations.AddField(
            model_name="seedeventtable",
            name="seed_event_table_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Seed Event Table"
            ),
        ),
        migrations.AddField(
            model_name="seedeventtable",
            name="seed_event_table_fr",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Seed Event Table"
            ),
        ),
        migrations.AddField(
            model_name="seedhead",
            name="seed_head_en",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Seed Head"
            ),
        ),
        migrations.AddField(
            model_name="seedhead",
            name="seed_head_fr",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Seed Head"
            ),
        ),
        migrations.AddField(
            model_name="seedpreparation",
            name="seed_preparation_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Seed Preparation"
            ),
        ),
        migrations.AddField(
            model_name="seedpreparation",
            name="seed_preparation_fr",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Seed Preparation"
            ),
        ),
        migrations.AddField(
            model_name="seedstorage",
            name="seed_storage_en",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Seed Storage"
            ),
        ),
        migrations.AddField(
            model_name="seedstorage",
            name="seed_storage_fr",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Seed Storage"
            ),
        ),
        migrations.AddField(
            model_name="seedviabilitytest",
            name="seed_viability_test_en",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Seed Viability Test",
            ),
        ),
        migrations.AddField(
            model_name="seedviabilitytest",
            name="seed_viability_test_fr",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Seed Viability Test",
            ),
        ),
        migrations.AddField(
            model_name="sowingdepth",
            name="sowing_depth_en",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Sowing Depth"
            ),
        ),
        migrations.AddField(
            model_name="sowingdepth",
            name="sowing_depth_fr",
            field=models.CharField(
                blank=True, max_length=25, null=True, verbose_name="Sowing Depth"
            ),
        ),
        # migrations.AddField(
        #     model_name="stratificationduration",
        #     name="stratification_duration_en",
        #     field=models.SmallIntegerField(
        #         blank=True, default=0, null=True, unique=True, verbose_name="Stratification Duration"
        #     ),
        # ),
        # migrations.AddField(
        #     model_name="stratificationduration",
        #     name="stratification_duration_fr",
        #     field=models.SmallIntegerField(
        #         blank=True, default=0, null=True, unique=True, verbose_name="Stratification Duration"
        #     ),
        # ),
        migrations.AddField(
            model_name="toxicityindicator",
            name="toxicity_indicator_en",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Toxicity Indicator"
            ),
        ),
        migrations.AddField(
            model_name="toxicityindicator",
            name="toxicity_indicator_fr",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Toxicity Indicator"
            ),
        ),
    ]
