# Generated by Django 5.2.7 on 2025-12-07 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0124_ecozone_ecozone_en_ecozone_ecozone_fr_and_more"),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name="stratificationduration",
    #         name="stratification_duration_en",
    #     ),
    #     migrations.RemoveField(
    #         model_name="stratificationduration",
    #         name="stratification_duration_fr",
    #     ),
    # ]
