# Generated by Django 5.2.7 on 2025-12-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project",
            "0125_remove_stratificationduration_stratification_duration_en_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nonnativespecies",
            unique_together={("latin_name", "english_name")},
        ),
        migrations.AddField(
            model_name="nonnativespecies",
            name="english_name_en",
            field=models.CharField(
                blank=True, max_length=75, null=True, verbose_name="English Name"
            ),
        ),
        migrations.AddField(
            model_name="nonnativespecies",
            name="english_name_fr",
            field=models.CharField(
                blank=True, max_length=75, null=True, verbose_name="English Name"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="nonnativespecies",
            unique_together={
                ("latin_name", "english_name"),
                ("latin_name", "english_name_en"),
                ("latin_name", "english_name_fr"),
            },
        ),
    ]
