# Generated by Django 5.2.7 on 2026-01-12 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0126_alter_nonnativespecies_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                ("phone", models.CharField(max_length=15, verbose_name="Phone")),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Order Date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("shipped", "Shipped"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total Price",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="project.customer",
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "price_at_purchase",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Price at Purchase",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="project.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "plant_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="project.plantprofile",
                        verbose_name="Plant Profile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Order Items",
                "unique_together": {("order", "plant_profile")},
            },
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_carts",
                        to="project.customer",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "plant_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.plantprofile",
                        verbose_name="Plant Profile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Shopping Carts",
                "unique_together": {("customer", "plant_profile")},
            },
        ),
    ]
