# Generated by Django 5.2.7 on 2026-03-20 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0126_alter_nonnativespecies_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NarrativeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=75, unique=True, verbose_name="Type"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantNarrative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "narrative_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="project.narrativetype",
                        verbose_name="Narrative Type",
                    ),
                ),
                (
                    "plant_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narratives",
                        to="project.plantprofile",
                        verbose_name="Plant Profile",
                    ),
                ),
            ],
        ),
    ]
