# Generated by Django 5.2.7 on 2026-01-12 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0127_customer_order_orderitem_shoppingcart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="phone",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="price_at_purchase",
        ),
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100, verbose_name="City"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=100,
                verbose_name="First Name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=100,
                verbose_name="Last Name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="postal_code",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=20,
                verbose_name="Postal Code",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="province",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=100,
                verbose_name="Province",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="donation_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Optional donation amount in addition to seed order.",
                max_digits=10,
                verbose_name="Donation Amount",
            ),
        ),
    ]
