# Generated by Django 5.2.7 on 2026-03-20 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0127_narrativetype_plantnarrative"),
    ]

    operations = [
        migrations.RenameField(
            model_name="narrativetype",
            old_name="type",
            new_name="narrative_type",
        ),
        migrations.AddField(
            model_name="narrativetype",
            name="narrative_type_en",
            field=models.CharField(
                blank=True, max_length=75, null=True, unique=True, verbose_name="Type"
            ),
        ),
        migrations.AddField(
            model_name="narrativetype",
            name="narrative_type_fr",
            field=models.CharField(
                blank=True, max_length=75, null=True, unique=True, verbose_name="Type"
            ),
        ),
    ]
