# Generated by Django 5.2.7 on 2026-01-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0128_rename_phone_customer_phone_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_shop_open",
                    models.BooleanField(
                        default=True, verbose_name="Is Shop Open for Orders"
                    ),
                ),
                (
                    "is_accepting_seeds",
                    models.BooleanField(
                        default=False, verbose_name="Is Accepting Seeds"
                    ),
                ),
            ],
        ),
    ]
