# Generated by Django 5.2.7 on 2026-03-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0128_rename_type_narrativetype_narrative_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantnarrative",
            name="published",
            field=models.BooleanField(default=False, verbose_name="Published"),
        ),
    ]
