# Generated by Django 5.2.7 on 2026-06-09

from django.db import migrations, models


def migrate_butterfly_names_forward(apps, schema_editor):
    ButterflySpecies = apps.get_model("project", "ButterflySpecies")

    for butterfly in ButterflySpecies.objects.all().iterator():
        update_fields = []
        english_name_en = getattr(butterfly, "english_name_en", None)
        english_name_fr = getattr(butterfly, "english_name_fr", None)

        if english_name_en and not butterfly.english_name:
            butterfly.english_name = english_name_en
            update_fields.append("english_name")

        if english_name_fr and not butterfly.french_name:
            butterfly.french_name = english_name_fr
            update_fields.append("french_name")

        if update_fields:
            butterfly.save(update_fields=update_fields)


def migrate_butterfly_names_backward(apps, schema_editor):
    ButterflySpecies = apps.get_model("project", "ButterflySpecies")

    for butterfly in ButterflySpecies.objects.all().iterator():
        update_fields = []

        if hasattr(butterfly, "english_name_en"):
            if butterfly.english_name and not butterfly.english_name_en:
                butterfly.english_name_en = butterfly.english_name
                update_fields.append("english_name_en")

        if hasattr(butterfly, "english_name_fr"):
            if butterfly.french_name and not butterfly.english_name_fr:
                butterfly.english_name_fr = butterfly.french_name
                update_fields.append("english_name_fr")

        if update_fields:
            butterfly.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0129_plantnarrative_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="butterflyspecies",
            name="french_name",
            field=models.CharField(
                blank=True, max_length=75, verbose_name="French Name"
            ),
        ),
        migrations.RunPython(
            migrate_butterfly_names_forward,
            migrate_butterfly_names_backward,
        ),
        migrations.RemoveField(
            model_name="butterflyspecies",
            name="english_name_en",
        ),
        migrations.RemoveField(
            model_name="butterflyspecies",
            name="english_name_fr",
        ),
    ]
