# Generated by Django 5.2.7 on 2026-01-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0129_librarystatus"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LibraryStatus",
            new_name="LibrarySetting",
        ),
    ]
