# Generated by Django 5.2.7 on 2026-01-14 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0130_rename_librarystatus_librarysetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderSeedApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seed_application",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Seed Application"
                    ),
                ),
            ],
            options={
                "ordering": ["seed_application"],
            },
        ),
        migrations.AlterField(
            model_name="librarysetting",
            name="is_accepting_seeds",
            field=models.BooleanField(default=False, verbose_name="Accepting Seeds"),
        ),
        migrations.AlterField(
            model_name="librarysetting",
            name="is_shop_open",
            field=models.BooleanField(
                default=True, verbose_name="Shop Open for Orders"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project.orderseedapplication",
                verbose_name="Order Application",
            ),
        ),
    ]
