# Generated by Django 5.2.7 on 2026-06-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0130_butterflyspecies_french_name_cleanup_translation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="butterflyspecies",
            name="inaturalist_taxon_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="iNaturalist Taxon ID"
            ),
        ),
    ]
