# Generated by Django 5.2.7 on 2026-06-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0131_butterflyspecies_inaturalist_taxon_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="butterflyspecies",
            name="french_name_source",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="French Name Source"
            ),
        ),
    ]
