# Generated by Django 5.2.7 on 2026-01-29 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0131_orderseedapplication_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderseedapplication",
            name="priority",
            field=models.SmallIntegerField(
                default=0,
                help_text="Lower numbers indicate higher priority. 0 means no priority.",
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="project.orderseedapplication",
                verbose_name="Order Application",
            ),
        ),
    ]
