# Generated by Django 5.2.7 on 2026-01-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0132_orderseedapplication_priority_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="notes",
        ),
        migrations.AddField(
            model_name="order",
            name="customer_note",
            field=models.TextField(blank=True, verbose_name="Customer Notes"),
        ),
    ]
