# Generated by Django 5.2.7 on 2026-02-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0135_require_customer_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=15, verbose_name="Phone"),
        ),
    ]
