# Generated by Django 5.2.7 on 2026-03-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0136_alter_customer_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="phone_number",
        ),
    ]
