# Generated by Django 5.2.7 on 2026-06-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0132_butterflyspecies_french_name_source"),
        ("project", "0138_stripewebhookevent_donation"),
    ]

    operations = []
