# Generated by Django 5.2.7 on 2026-06-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0139_merge_20260626_0310"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarysetting",
            name="is_accepting_donations",
            field=models.BooleanField(
                default=False, verbose_name="Accepting Donations"
            ),
        ),
    ]
