# Generated by Django 6.0.7 on 2026-07-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0140_librarysetting_is_accepting_donations"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantprofile",
            name="seed_per_envelope",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Seed Per Envelope"
            ),
        ),
    ]
