# Generated by Django 6.0.7 on 2026-07-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0141_plantprofile_seed_per_envelope"),
    ]

    operations = [
        migrations.AddField(
            model_name="beespecies",
            name="english_name",
            field=models.CharField(
                blank=True, max_length=75, verbose_name="English Name"
            ),
        ),
        migrations.AddField(
            model_name="beespecies",
            name="french_name",
            field=models.CharField(
                blank=True, max_length=75, verbose_name="French Name"
            ),
        ),
    ]
