# Generated by Django 6.0.7 on 2026-07-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0142_beespecies_english_name_beespecies_french_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="beespecies",
            name="french_name_source",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="French Name Source"
            ),
        ),
    ]
