# Generated by Django 6.0.7 on 2026-07-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0143_beespecies_french_name_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="beespecies",
            name="inaturalist_taxon_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="iNaturalist Taxon ID"
            ),
        ),
    ]
