# Generated by Django 6.0.7 on 2026-07-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0144_beespecies_inaturalist_taxon_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
