#!/usr/bin/env python3
"""Load JSON fixtures generated by scripts/dump-data.py into a Django database.

Usage examples:
  scripts/load-data.py
  scripts/load-data.py --database default --input-dir scripts/data
  scripts/load-data.py --continue-on-error --skip-missing
"""

from __future__ import annotations

import argparse
import io
import os
import re
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
DEFAULT_INPUT_DIR = BASE_DIR / "scripts" / "data"

# Load order is intentional for referential integrity.
MODEL_LABELS = [
    "auth.permission",
    "auth.group",
    "project.beespecies",
    "project.bloomcolour",
    "project.butterflyspecies",
    "project.conservationstatus",
    "project.ecozone",
    "project.growthhabit",
    "project.harvestingindicator",
    "project.harvestingmean",
    "project.lighting",
    "project.narrativetype",
    "project.nonnativespecies",
    "project.onecultivar",
    "project.packagingmeasure",
    "project.plantlifespan",
    "project.plantmorphology",
    "project.seedeventtable",
    "project.seedhead",
    "project.seedpreparation",
    "project.seedstorage",
    "project.seedstoragelabelinfo",
    "project.seedviabilitytest",
    "project.sowingdepth",
    "project.stratificationduration",
    "project.toxicityindicator",
    "project.plantprofile",
    "project.obsoletenames",
    "project.plantcomplementary",
    "project.plantnarrative",
    "project.plantimage",
    "project.projectuser",
    "project.plantcollection",
]

INSTALLED_RE = re.compile(r"Installed\s+(\d+)\s+object\(s\)")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Load selected fixtures into a Django database."
    )
    parser.add_argument(
        "--database",
        default="default",
        help="Django database alias (default: default)",
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=DEFAULT_INPUT_DIR,
        help=f"Fixture directory (default: {DEFAULT_INPUT_DIR})",
    )
    parser.add_argument(
        "--continue-on-error",
        action="store_true",
        help="Continue loading remaining fixtures if one fails.",
    )
    parser.add_argument(
        "--skip-missing",
        action="store_true",
        help="Skip missing fixture files instead of failing.",
    )
    parser.add_argument(
        "--flush-first",
        action="store_true",
        help="Flush target database before loading fixtures.",
    )
    parser.add_argument(
        "--confirm-flush",
        action="store_true",
        help="Required with --flush-first to prevent accidental data wipe.",
    )
    return parser.parse_args()


def setup_django() -> None:
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "main.settings")
    sys.path.insert(0, str(BASE_DIR))
    import django

    django.setup()


def model_label_to_filename(model_label: str) -> str:
    return model_label.replace(".", "_") + ".json"


def validate_database_alias(alias: str) -> None:
    from django.conf import settings

    if alias not in settings.DATABASES:
        choices = ", ".join(sorted(settings.DATABASES.keys()))
        raise SystemExit(
            f"Invalid database alias '{alias}'. Available aliases: {choices}"
        )


def load_fixture(*, fixture_path: Path, database: str) -> tuple[int, str]:
    from django.core.management import call_command

    output = io.StringIO()
    call_command(
        "loaddata",
        str(fixture_path),
        database=database,
        verbosity=1,
        stdout=output,
    )
    text = output.getvalue().strip()
    match = INSTALLED_RE.search(text)
    count = int(match.group(1)) if match else 0
    return count, text


def flush_database(*, database: str) -> None:
    from django.core.management import call_command

    call_command(
        "flush",
        database=database,
        interactive=False,
        verbosity=1,
        reset_sequences=False,
        allow_cascade=True,
    )


def main() -> int:
    args = parse_args()
    setup_django()

    from django.apps import apps
    from django.core.management.base import CommandError

    validate_database_alias(args.database)

    if args.flush_first and not args.confirm_flush:
        raise SystemExit(
            "Refusing to flush without explicit confirmation. "
            "Use --flush-first --confirm-flush"
        )

    if not args.input_dir.exists() or not args.input_dir.is_dir():
        raise SystemExit(f"Input directory does not exist: {args.input_dir}")

    missing_labels = [label for label in MODEL_LABELS if apps.get_model(label) is None]
    if missing_labels:
        raise SystemExit(
            "Invalid model labels in load configuration: " + ", ".join(missing_labels)
        )

    failures: list[tuple[str, str]] = []
    skipped: list[str] = []
    loaded_count = 0
    total_objects = 0

    print(f"Loading fixtures from: {args.input_dir}")
    print(f"Using database alias: {args.database}")

    if args.flush_first:
        print(f"Flushing database alias: {args.database}")
        flush_database(database=args.database)
        print("Flush completed.")

    for model_label in MODEL_LABELS:
        fixture_path = args.input_dir / model_label_to_filename(model_label)

        if not fixture_path.exists():
            message = f"missing fixture: {fixture_path.name}"
            if args.skip_missing:
                skipped.append(model_label)
                print(f"SKIP {model_label:<40} -> {message}")
                continue
            failures.append((model_label, message))
            print(f"ERR  {model_label:<40} -> {message}")
            if not args.continue_on_error:
                break
            continue

        try:
            row_count, details = load_fixture(
                fixture_path=fixture_path,
                database=args.database,
            )
            loaded_count += 1
            total_objects += row_count
            print(
                f"OK   {model_label:<40} -> {fixture_path.name} ({row_count} objects)"
            )
            if details:
                print(f"     {details}")
        except (CommandError, OSError) as exc:
            failures.append((model_label, str(exc)))
            print(f"ERR  {model_label:<40} -> {exc}")
            if not args.continue_on_error:
                break
        except KeyboardInterrupt:
            print("Interrupted by user.")
            return 130

    print("\nSummary")
    print(f"  Fixtures configured: {len(MODEL_LABELS)}")
    print(f"  Fixtures loaded: {loaded_count}")
    print(f"  Objects installed: {total_objects}")
    print(f"  Skipped: {len(skipped)}")
    print(f"  Failures: {len(failures)}")

    if skipped:
        print("  Skipped model labels:")
        for label in skipped:
            print(f"    - {label}")

    if failures:
        print("  Failed model labels:")
        for label, error in failures:
            print(f"    - {label}: {error}")
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
